services:
  whisperx:
    image: jim60105/whisperx:latest
    container_name: whisperx-service
    volumes:
      - ../data/videos/audio:/app/audio
      - ../data/videos/transcripts:/app/output
    environment:
      - WHISPER_MODEL=base
      - DEVICE=cpu  # Change to 'cuda' if you have GPU support
    restart: unless-stopped
    command: ["--model", "base", "--language", "en", "--device", "cpu", "--output_format", "json", "--output_dir", "/app/output"]
