version: "3.9"

services:
  whisperx:
    build: 
      context: .
      dockerfile: Dockerfile.whisperx
    container_name: whisperx-api
    ports:
      - "9010:9000"
    environment:
      - WHISPER_MODEL=base
      - DEVICE=cpu
      - COMPUTE_TYPE=float32
      - TIMEOUT=3600  # 1 hour timeout for large videos
    volumes:
      - whisperx-cache:/root/.cache
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-api
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0

  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    container_name: mongodb-atlas-local
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin123
      - MONGODB_INITDB_DATABASE=videosegment
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

volumes:
  whisperx-cache:
  ollama-data:
  mongodb-data:
  mongodb-config:

