version: "3.9"

services:
  whisperx:
    build: .
    container_name: whisperx-api
    ports:
      - "9010:9000"
    environment:
      - WHISPER_MODEL=base
      - DEVICE=cpu
      - COMPUTE_TYPE=float32
    restart: unless-stopped

